### PR TITLE
Aditya Raman - 1.0.2

### PR DESCRIPTION
**Pull request by ramanaditya**

### CODE REVIEW

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you. Please could you rename the file to use `-` not `_`, there is an example in `README.md`

**Review by eddiejaoude — CHANGES_REQUESTED** [review]
Thank you, but you now have added capitals. Please can you make it lower case. There is an example in the README.md

**Comment by ramanaditya** [comment]
- lower case done

**Review by eddiejaoude — APPROVED** [review]
LGTM 👍

**Pull request merged**
